---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/_data/data.service.json
  label: Консультации
- type: document
  path: src/_data/data.contacts.json
  label: Контакты
- type: document
  path: src/_data/data.me.json
  label: Обо мне
- type: heading
  label: данные для поисковиков
- type: document
  path: src/_data/metadata.json
  label: Метаданные
upload_dir: src/img/photo
public_path: "/src/img/photo"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
